import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import LayoutWrapper from "@/components/layout/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { createClient } from "@/utils/supabase/server";
import { TooltipProvider } from "@/components/ui/tooltip";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();

  // Fetch settings
  const { data: storeSettings } = await supabase
    .from("store_settings")
    .select("*")
    .single();

  // Check maintenance mode
  // if (storeSettings?.maintenance_mode) {
  //   const {
  //     data: { user },
  //   } = await supabase.auth.getUser();

  //   if (user) {
  //     const { data: profile } = await supabase
  //       .from("profiles")
  //       .select("role")
  //       .eq("id", user.id)
  //       .single();

  //     if (profile?.role !== "admin") {
  //       return (
  //         <html lang="en">
  //           <body
  //             className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //           >
  //             <MaintenancePage />
  //           </body>
  //         </html>
  //       );
  //     }
  //   } else {
  //     return (
  //       <html lang="en">
  //         <body
  //           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //         >
  //           <MaintenancePage />
  //         </body>
  //       </html>
  //     );
  //   }
  // }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <LayoutWrapper storeSettings={storeSettings}>
            {children}
          </LayoutWrapper>
          <Toaster />
        </TooltipProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
